### PR TITLE
Build WASM wheel

### PR DESCRIPTION
**Pull request by kafonek**
closes https://github.com/y-crdt/ypy/issues/90.  

I believe Pyodide needs a wheel built with a specific version of Python and specific version of emscripten that match the Pyodide version. For latest Pyodide (0.21.3, released Sep 15 2022), and going back through Pyodide 0.20.0 (Aug 9) that is Python 3.10.2 and emscripten 3.14.1.  If we wanted to support earlier versions, we would need to review [Pyodide changelog](https://pyodide.org/en/stable/project/changelog.html) to make a matrix of python/emscripten versions to build the wasm wheel with.

See https://github.com/kafonek/ypy/actions/runs/3452230687/jobs/5761992236 for an example of the wheel being built. I don't understand why that's building a wasm wheel for py310 and py311 there but it doesn't hurt anything 🤷‍♂️ .

### CODE REVIEW

**Comment by davidbrochart** [comment]
Sorry for the late answer @kafonek, I think Thorsten is the best person to review this.

**Comment by DerThorsten** [comment]
looks good to me, but disclaimer: I know nothing about rust

**Comment by davidbrochart** [comment]
Maybe @Waidhoferj wants to have a look too?

**Review by Waidhoferj — APPROVED** [review]
Looks good! I'm excited to see Ypy in the browser!

**Comment by kafonek** [comment]
Thanks all, thanks for merging @Waidhoferj . I'm also excited to write up some demo's of y-py on client (pyodide) and server (fastapi). Are you going to bump the version, or want to manually push out the 0.5.4 emscripten wheel to pypi?

**Pull request merged**
