### PR TITLE
v0.5.5 Release

### PR DESCRIPTION
**Pull request by Waidhoferj**
Release a new version of Ypy to make the WASM wheel build available to @kafonek

### CODE REVIEW

**Review by dmonad — APPROVED** [review]
LGTM!

**Comment by davidbrochart** [comment]
Should we update `yrs` and `lib0` to `0.13.0`?

**Comment by Horusiath** [comment]
For sure it should use yrs v0.12.2, since it's no brainer and fixes #28. However yrs v0.13 is much bigger change.

**Comment by davidbrochart** [comment]
Thanks @Waidhoferj.
Are we going to publish wheels for Python 3.11?

**Comment by Waidhoferj** [comment]
@davidbrochart I think the changes in #88 should create wheels for 3.11.

**Review by davidbrochart — APPROVED** [review]

**Comment by davidbrochart** [comment]
@Waidhoferj I see a [GitHub release](https://github.com/y-crdt/ypy/releases/tag/v0.5.5) but nothing on PyPI: https://pypi.org/project/y-py/#history.

**Comment by Waidhoferj** [comment]
@davidbrochart there was an issue with the platform label created by the wasm build script. @kafonek is handling it in #96

**Comment by davidbrochart** [comment]
Yes sorry, I just saw it.

**Comment by SylvainCorlay** [comment]
It seems 0.5.5 is still not on PyPI. Anything blocking the follow-up PR to get merged?

**Pull request merged**
